BEGIN TRANSACTION;

CREATE TABLE public.shoes (
    "name" VARCHAR(100) not null UNIQUE PRIMARY key,
     "id" serial NOT NULL,
    price NUMERIC(5,2) not NULL,
    "desc" text not NULL,
    img text not null,
    gender text not null,
    "type" VARCHAR(100) not null
);

INSERT INTO public.shoes (name, id, price, "desc", img, gender, type) VALUES
	('Nike Air Max 270', 1, 160.00, 'Nikes first lifestyle Air Max brings you style, comfort and big attitude in the Nike Air Max 270. The design draws inspiration from Air Max icons, showcasing Nikes greatest innovation with its large window and fresh array of colors. ', 'https://res.cloudinary.com/ds4wntnyf/image/upload/v1690994303/airMax270_wq1wj6.webp', 'men&women', 'shoes'),
	('Nike Air VaporMax 2023 Flyknit', 2, 210.00, 'Have you ever walked on Air? Step into the Air VaporMax 2023 to see how it''s done. The innovative tech is revealed through the perforated sockliner (pull it out to see more). The stretchy Flyknit upper is made with at least 20% recycled content by weight.', 'https://res.cloudinary.com/ds4wntnyf/image/upload//c_thumb,w_592,h_592/v1690996209/air-vapormax-2023-flyknit-mens-shoes-3q1qZg_strtgy.jpg', 'men&women', 'shoes'),
	('Ja 1 "Fuel"', 3, 110.00, 'Ja Morant became the superstar he is today by repeatedly sinking jumpers on crooked rims, jumping on tractor tires and dribbling through sun-stained traffic cones in steamy South Carolina summers. The Ja 1 is a testament to his rise. With Zoom Air, it supports bunny hops and hyper speed without sacrificing comfort, so that you can control your own destiny on the court, Ja-style. This special design pays homage to Ja’s motivation—the Morant family and the warm memories they created back in the day in the backyard.', 'https://res.cloudinary.com/ds4wntnyf/image/upload//c_thumb,w_592,h_592/v1690996798/ja-1-fuel-basketball-shoes-ftCb5g_ynqpqe.jpg', 'men&women', 'shoes'),
	('LeBron Soldier 14', 4, 119.97, 'LeBron has always been crystal clear on his Soldier franchise: He wants to feel light, secure and in control. The LeBron Soldier 14 delivers, with a stripped-down, deconstructed design built to support a player with LeBron''s force. A smooth, responsive cushioning system gives him a sensation that''s distinct from his game shoe.', 'https://res.cloudinary.com/ds4wntnyf/image/upload//c_thumb,w_592,h_592/v1690998395/lebron-soldier-14-basketball-shoes-qkSRCH_ny7v75.jpg', 'men&women', 'shoes'),
	('Nike On Deck', 5, 22.97, 'The Nike On Deck is a go-to flip flop with its easy-to-wear, no frills design. The rounded toe post limits chaffing while the foam midsole delivers the perfect amount of lightweight cushioning. Its Waffle inspired tread adds a heritage touch that gives you traction and durability.', 'https://res.cloudinary.com/ds4wntnyf/image/upload//c_thumb,w_592,h_592/v1691726522/on-deck-mens-slides-McrHWg_fsbsts.jpg', 'men', 'shoes'),
	('Nike Victori One', 6, 22.97, 'You''ve played hard. You''ve sweated. You''ve given your all. Now there''s just one last thing—you have to hit the showers. Don''t worry, we got your back with the Nike Victori One. Its 1-piece foam design feels soft and comfortable while traction patterns on the sole help with wet surfaces. They dry quickly too, so no one will know you''ve just stepped from the showers as you slide up to the party.', 'https://res.cloudinary.com/ds4wntnyf/image/upload//c_thumb,w_592,h_592/v1691802486/victori-one-mens-shower-slides-ZD82Jn_bk9mkn.jpg', 'men', 'shoes'),
	('Nike Cortez', 7, 90.00, 'You''ve played hard. You''ve sweated. You''ve given your all. Now there''s just one last thing—you have to hit the showers. Don''t worry, we got your back with the Nike Victori One. Its 1-piece foam design feels soft and comfortable while traction patterns on the sole help with wet surfaces. They dry quickly too, so no one will know you''ve just stepped from the showers as you slide up to the party.', 'https://res.cloudinary.com/ds4wntnyf/image/upload//c_thumb,w_592,h_592/v1691802823/cortez-mens-shoes-SxhPXX_lhwc4b.jpg', 'men&women', 'shoes'),
	('Nike Dunk Low Premium MF', 8, 120.00, 'Created for the hardwood but taken to the streets, the ''80s b-ball icon returns with classic details and throwback hoops flare. Channeling vintage style back onto the streets, its padded, low-cut collar lets you take your game anywhere—in comfort.', 'https://res.cloudinary.com/ds4wntnyf/image/upload//c_thumb,w_592,h_592/v1691803427/dunk-low-premium-mf-womens-shoes-QwvHrM_kd8zd0.jpg', 'women', 'shoes'),
	('Nike Victori One x Nike United', 10, 40.00, 'From the beach to gardening to lounging around the house, the Victori One is all about lightweight comfort that’s easy to wear. Soft foam in the strap and midsole gives you a more comfortable feel, while the grip pattern helps hold your feet in place as you walk. Time to celebrate the moment in off-pitch style.', 'https://res.cloudinary.com/ds4wntnyf/image/upload//c_thumb,w_592,h_592/v1691814665/victori-one-x-nike-united-womens-slides-dLThzx_h4y4tu.jpg', 'women', 'shoes'),
	('Nike Calm', 9, 50.00, 'When it comes to these slides, it''s all in the name. Take a deep breath and slip into a minimalist look with maximalist cushioning. Contoured foam is seamlessly created from one piece, and cradles your feet to help keep them in place. To top it off, the water-friendly design dries quickly—making it ideal for relaxing poolside. You get all of the style, none of the effort. It''s time for some Calm.', 'https://res.cloudinary.com/ds4wntnyf/image/upload//c_thumb,w_592,h_592/v1691814177/calm-womens-slides-7XtJSh_oiqw80.jpg', 'women', 'shoes');




COMMIT;